# Generated by Django 4.2.4 on 2023-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='Статья', to='articles.tag', verbose_name='Тема'),
        ),
    ]
