# Generated by Django 4.2.4 on 2023-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='Статья', through='articles.ArticleScope', to='articles.tag', verbose_name='Тема'),
        ),
    ]
